In [39]:
import os
import torch
# get the directory of the current script
script_dir = '' # os.path.dirname(os.path.abspath(__file__))

# Construct the path to the data file
data_file_path = os.path.join(script_dir, '../data/input.txt')

# read it in to inspect it
with open(data_file_path, 'r', encoding='utf-8') as f:
    text = f.read()

In [40]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [41]:
#create a mapping of characters to integers
stoi = {c: i for i, c in enumerate(chars)}
itos = {i: c for i, c in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda x: ''.join([itos[i] for i in x])

encodedHello = encode('hello')
print(encodedHello)
print(decode(encodedHello))


[46, 43, 50, 50, 53]
hello


In [42]:
# incode entire training text dataset
data = torch.tensor(encode(text), dtype=torch.long)

In [43]:
# Let's now split u[p the data into train and validation sets
n = int( 0.9 * len(data))
train_data, val_data = data[:n], data[n:]

print(train_data.shape, val_data.shape)
print('train_data[:100]')
print(train_data[:100])

torch.Size([1003854]) torch.Size([111540])
train_data[:100]
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [44]:
block_size = 8
train_dataset = data.unfold(0, block_size + 1, block_size)

In [45]:
for train_data in train_dataset:
    for t in range(block_size):
        context = train_data[:t+1]
        target = train_data[t+1]
        
        print(f'when input is {context}, target is {target}')
    break

when input is tensor([18]), target is 47
when input is tensor([18, 47]), target is 56
when input is tensor([18, 47, 56]), target is 57
when input is tensor([18, 47, 56, 57]), target is 58
when input is tensor([18, 47, 56, 57, 58]), target is 1
when input is tensor([18, 47, 56, 57, 58,  1]), target is 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]), target is 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), target is 58


In [46]:
torch.manual_seed(1337)
batch_size = 4  # how many independent sequences will we process in parallel?
block_size = 8  # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs')
print(xb.shape)
print(xb)
print('targets')
print(yb.shape)
print(yb)


inputs
torch.Size([4, 8])
tensor([[18, 47, 56, 57, 58,  1, 15, 47],
        [18, 47, 56, 57, 58,  1, 15, 47],
        [18, 47, 56, 57, 58,  1, 15, 47],
        [18, 47, 56, 57, 58,  1, 15, 47]])
targets
torch.Size([4, 8])
tensor([[47, 56, 57, 58,  1, 15, 47, 58],
        [47, 56, 57, 58,  1, 15, 47, 58],
        [47, 56, 57, 58,  1, 15, 47, 58],
        [47, 56, 57, 58,  1, 15, 47, 58]])


In [128]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(BigramLanguageModel, self).__init__()
        self.embeddings_table = nn.Embedding(vocab_size, embedding_dim)
   
        
    def forward(self, idx, targets = None):
        # idx and targets are both (B, T) tensors of integers
        logits = self.embeddings_table(idx)  # (B, T, C)
        if targets is None:
          loss = None
        else:
          B, T, C = logits.shape
          logits = logits.view(B * T, C)
          targets = targets.view(B * T)
          loss = F.cross_entropy(logits, targets)
        return logits, loss
      
    def generate(self, x, max_new_tokens=100):
      for _ in range(max_new_tokens):
          logits, loss = self.forward(x)
  
          logits = logits[:, -1, :]
          probs = F.softmax(logits, dim=-1)
          x = torch.cat([x[:, 1:], torch.multinomial(probs, num_samples=1)], dim=1)
      return x
      


In [127]:
m = BigramLanguageModel(vocab_size, vocab_size)
logits, loss = m(xb, yb)
print(loss)
idx = torch.zeros(1, 1, dtype=torch.int)
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))  

tensor(4.4032, grad_fn=<NllLossBackward0>)


RuntimeError: Tensors must have same number of dimensions: got 2 and 1